plugins {
    id 'idea'
    id 'maven-publish'
    id "consumer.conventions"
    alias(libs.plugins.loom)
    alias(libs.plugins.curseforgegradle)
    alias(libs.plugins.minotaur)
}

base {
    archivesName = "${mod_name}-fabric-${libs.versions.minecraft.release.get()}"
}

loom {
    def awFile = project(":common").file("src/main/resources/${mod_id}.accesswidener")
    if (awFile.exists()) {
        accessWidenerPath = awFile
    }

    runs {
        configureEach {
            ideConfigGenerated(true)
            runDir("run")
        }
        client {
            client()
            setConfigName("Fabric Client")
        }
        server {
            server()
            setConfigName("Fabric Server")
        }
    }
}

repositories {
    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
    }
}

dependencies {
    minecraft libs.minecraft
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${libs.versions.parchment.minecraft.get()}:${libs.versions.parchment.release.get()}@zip")
    }
    modImplementation libs.fabric.loader
    modImplementation libs.fabric.api
}

modrinth {
    projectId = modrinth_project_id
    versionName = "fabric-${libs.versions.minecraft.release.get()}-${version}"
    versionNumber = "${libs.versions.minecraft.release.get()}-${version}+fabric"
    versionType = publish_type
    uploadFile.set(tasks.remapJar)
    gameVersions = List.of(libs.versions.publish.range.get().split(","))
    loaders = List.of("fabric")
    changelog = rootProject.file("changelog.md").text
    additionalFiles = List.of(tasks.named("sourcesJar"), tasks.named("javadocJar"))
    detectLoaders = false
    dependencies {
        required.project "fabric-api"
    }
    debugMode = publish_debug.toBoolean()
}

tasks.register("curseforge", net.darkhax.curseforgegradle.TaskPublishCurseForge) {
    group = "publishing"

    disableVersionDetection()
    apiToken = findProperty("curseforge_publishing_token")
    def mainFile = upload(curseforge_project_id, tasks.remapJar)
    mainFile.displayName = "fabric-${libs.versions.minecraft.release.get()}-${version}"
    mainFile.releaseType = publish_type
    mainFile.changelog = rootProject.file("changelog.md").text
    mainFile.changelogType = "markdown"
    mainFile.addModLoader("Fabric")
    mainFile.addJavaVersion("Java ${java.toolchain.languageVersion.get()}")
    mainFile.addGameVersion(libs.versions.minecraft.release.get())
    debugMode = publish_debug.toBoolean()

    dependsOn(tasks.remapJar)
}
