import org.groovymc.modsdotgroovy.gradle.tasks.AbstractGatherPlatformDetailsTask

plugins {
    id 'idea'
    id 'maven-publish'
    id 'fabric-loom' version '1.1-SNAPSHOT'
    id "consumer.conventions"
    alias(libs.plugins.mdg)
}

modsDotGroovy {
    platform(org.groovymc.modsdotgroovy.types.core.Platform.FABRIC)
    inferGather.set(false)
    multiplatform {
        from(":Common")
    }
    apply()
}

tasks.named("gatherFabricPlatformDetails", AbstractGatherPlatformDetailsTask).configure {
    minecraftVersion = libs.versions.minecraft.release
    platformVersion = libs.versions.fabric.loader
}

base {
    archivesName = "${mod_id}-fabric-${libs.versions.minecraft.release.get()}-${mod_version}"
}

dependencies {
    minecraft "com.mojang:minecraft:${libs.versions.minecraft.release.get()}"
    mappings loom.officialMojangMappings()
    modImplementation(libs.fabric.loader)
    modImplementation(libs.fabric.api)

    runtimeOnly("com.github.llamalad7.mixinextras:mixinextras-fabric:0.2.0-beta.9")
    modImplementation("mysticdrew:common-networking-fabric:1.0.1-1.20.1")
    modImplementation("dev.dhyces.trimmed:trimmed-fabric-1.20.1:2.1.4")
}

loom {
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("run")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("run")
        }
    }

    mixin {
        defaultRefmapName = "${mod_id}.refmap.json"
    }
}