[versions]
minecraft_release = "26.2"
minecraft_range = "[26.2,26.3.0-snapshot)"
publish_range = "26.2"

parchment_release = "2025.10.12"
parchment_minecraft = "1.21.10"

javafml_range = "[3,)"
neoforge_release = "26.2.0.57"
neoforge_range = "[26.2.0.57,26.3.0.0-alpha)"

fabric_loader = "0.19.3"
fabric_api_release = "0.156.0+26.2"
fabric_api_range = "[0.156.0,)"

neoform = "26.2-2"
mixin = "0.17.3+mixin.0.8.7"
mixinextras = "0.5.4"
asm = "9.9.1"

jetbrains_annotations = "26.1.0"
jspecify = "1.0.0"

moddev = "2.0.143"
loom = "1.17.9"

curseforgegradle = "1.1.28"
minotaur = "2.+"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft_release" }
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge_release" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api_release" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

mixin = { module = "net.fabricmc:sponge-mixin", version.ref = "mixin" }
mixinextras_common = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixinextras" }

jetbrains_annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains_annotations" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }

[plugins]
moddev = { id = "net.neoforged.moddev", version.ref = "moddev" }
loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
curseforgegradle = { id = "net.darkhax.curseforgegradle", version.ref = "curseforgegradle" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
