modLoader = "javafml"
loaderVersion = "[3,)"
license = "MIT"
issueTrackerURL = "https://github.com/dhyces/waxable-coral/issues"

[[mods]]
modId = "waxablecoral"
displayName = "Waxable Coral"
authors = "dhyces"
version = "3.0.0"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/waxable-coral"
sourcesUrl = "https://github.com/dhyces/waxable-coral"
iconFile = "assets/waxablecoral/icon.png"
description = "Wax your coral! Stays alive even when it's dry!"

[[dependencies.waxablecoral]]
modId = "minecraft"
versionRange = "[26.2,26.3.0-snapshot)"
type = "required"

[[dependencies.waxablecoral]]
modId = "neoforge"
versionRange = "[26.2.0.57,26.3.0.0-alpha)"
type = "required"
