plugins {
    id 'idea'
    id "shared.conventions"
    alias(libs.plugins.moddev)
}

base {
    archivesName = "${mod_name}-common-${libs.versions.minecraft.release.get()}"
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
    testCompileOnly.extendsFrom(compileOnly)
}

neoForge {
    neoFormVersion = libs.versions.neoform.get()
    // Automatically enable AccessTransformers if the file exists
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
//    parchment {
//        minecraftVersion = libs.versions.parchment.minecraft.get()
//        mappingsVersion = libs.versions.parchment.release.get()
//    }
}

// Vanilla depends on ASM 9.6, MDG makes that a 'strict' version constraint,
// but mixin needs newer ASM so we override that here.
configurations.configureEach {
    resolutionStrategy.eachDependency { details ->
        if (details.requested.group == "org.ow2.asm") {
            details.useVersion(libs.versions.asm.get())
            details.because("Mixin requires new ASM")
        }
    }
}

dependencies {
    compileOnly libs.mixin
    compileOnly libs.mixinextras.common
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    sourceSets.main.resources.sourceDirectories.forEach {
        commonResources it
    }
}
